app = "astromonkey"
primary_region = "ord"

[[services]]
  internal_port = 3000
  protocol = "tcp"

[deploy]
  strategy = "rolling"  # Choose your preferred deployment strategy

[experimental]
  dockerfile = "Dockerfile"